version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "installing something"
    pre_build:     
        commands:
            - echo "we are in the prebuild phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - ls -la
            - cat index.html || echo "index.html not found"
            - if [ -f index.html ]; then grep -fq "Congratulations" index.html; else echo "index.html not found"; fi
    post_build:
        commands:
            - echo "we are in the post build phase"
